//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Models.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDanhMuc
    {
        public int ID { get; set; }
        public Nullable<int> Tuan { get; set; }
        public Nullable<int> TongCapCTS { get; set; }
        public Nullable<System.DateTime> TuNgay { get; set; }
        public Nullable<System.DateTime> DenNgay { get; set; }
        public Nullable<int> CapMoi { get; set; }
        public Nullable<int> GiaHan { get; set; }
        public Nullable<int> CapLai { get; set; }
        public Nullable<int> ThuHoi { get; set; }
        public Nullable<int> CapBu { get; set; }
        public Nullable<int> CapLoi { get; set; }
        public Nullable<int> NgoaiGiao { get; set; }
        public Nullable<int> DungThu { get; set; }
        public Nullable<int> MoKhoa { get; set; }
        public Nullable<int> KhoiPhuc { get; set; }
        public Nullable<int> TamDung { get; set; }
        public Nullable<int> KDHN { get; set; }
        public Nullable<int> CNTPCM { get; set; }
        public Nullable<int> KDTPHCM { get; set; }
        public Nullable<int> E_Invoice { get; set; }
        public Nullable<int> KDHNeinvoice { get; set; }
        public Nullable<int> NhomHDeinvoice { get; set; }
        public Nullable<int> TPHCM { get; set; }
        public Nullable<int> Co_van { get; set; }
        public Nullable<int> EBH { get; set; }
        public Nullable<int> NhapHS { get; set; }
        public Nullable<decimal> CPN { get; set; }
        public Nullable<decimal> DoanhThuHN { get; set; }
        public Nullable<decimal> DoanhThuCNHCM { get; set; }
        public Nullable<decimal> CongNoHN { get; set; }
        public Nullable<decimal> CongNoCNHCM { get; set; }
        public Nullable<int> CBCNHT { get; set; }
        public Nullable<int> CBTNHT { get; set; }
        public Nullable<int> ThueHT { get; set; }
        public Nullable<int> HoaDonHT { get; set; }
        public Nullable<int> Co_VanHT { get; set; }
        public Nullable<int> HaiQuanHT { get; set; }
        public Nullable<int> EBHHT { get; set; }
        public Nullable<int> GDKHT { get; set; }
        public Nullable<int> KTTTTD { get; set; }
        public Nullable<int> TongHT { get; set; }
        public Nullable<int> NhomCO { get; set; }
        public Nullable<int> NhomHD { get; set; }
        public Nullable<System.DateTime> Ngaytao { get; set; }
        public Nullable<int> CKSDoiSoat { get; set; }
        public Nullable<int> E_invoiceDoiSoat { get; set; }
        public Nullable<int> EBHDoiSoat { get; set; }
        public Nullable<int> Co_vanDoiSoat { get; set; }
        public Nullable<int> MoKhoaDoiSoat { get; set; }
        public Nullable<int> CKSHeThong { get; set; }
        public Nullable<int> E_invoiceHeThong { get; set; }
        public Nullable<int> Co_vanHeThong { get; set; }
        public Nullable<int> MoKhoaHeThong { get; set; }
        public Nullable<int> EBHHeThong { get; set; }
    }
}
